### ISSUE TITLE
Problem in instalation VCRUNTIME140.dll 

### ISSUE THREAD

**Issue by arthitag** [hiili/WindowsTorch#1]
When I run luajit I get an error saying "VCRUNTIME140.dll is missing from your computer".
I followed the instructions on this page:
https://answers.microsoft.com/en-us/windows/forum/windows_10-hardware/vcruntime140dll-missing/2b061a41-e9f6-48f7-abee-28193cd3b60e
and downloaded this  Visual C++ Redistributable Package
http://download.microsoft.com/download/0/5/6/056dcda9-d667-4e27-8001-8a0c6971d6b1/vcredist_x64.exe
However, installing this doesn't seem to resolve the issue. I am still getting the same error. 
Will appreciate any help. 
I am new to windows and visual studio. Thanks for this version of Torch

**Comment by hiili** [comment]
_Edit:_ I added the (hopefully) correct dlls to the bin directory (in both 32-bit and 64-bit branches), so now you should not need to install anything additional. @arthitag could you re-download and see if it works now?

Hi arthitag, and thanks for testing the build! Indeed, I haven't yet had an opportunity to test it on a fully clean machine.

First, these are built with Visual Studio 2015 Update 3, so you should download the VS runtime for that version. More specifically, could you try the "Microsoft Visual C++ Redistributable Packages for Visual Studio 2015 Update 3" download from https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads and then report back? Thanks!

Once we find the correct download, I will add that information to the readme file. And sorry for not already mentioning the correct VS version in the readme!

Also, which build (branch) are you trying to use?
